# Generated by Django 5.2.7 on 2025-11-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetail",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
